export const QueryKeys = {
  getUsersForDriverActionsKey: "getUserForDriverActions",
  getDriverForUpdateKey: "getDriverForUpdate",
  getDriver: "getDriver",
  getDriverForDelete: "getDriverForDelete",
  getAllUser: "getAllUsers",
  getUserById: "getUserById",
  getUserByIdForUpdate: "getUserByIdForUpdate",
  getUserByIdForDelete: "getUserByIdForDelete",
  getCargoForOfferPost: "getCargoForOfferPost",
  getCargosForDriver: "getCargosForDriver",
  getCargosForAdmin: "getCargosForAdmin",
  getOffersToCargo: "getOffersToCargo",
  getOffersOfDriver: "getOffersOfDriver",
  getAllOffers: "getAllOffers",
  getOfferForResponse: "getOfferForResponse",
  getUsersForChat: "getUsersForChat",
  getMessagesForChat: "getMessagesForChat",
  getDriverForLengthChange: "getDriverForLengthChange",
};
